server:
  port: 8082



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/assn_system?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  #配置文件大小限制
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 10MB
      max-request-size:  100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xrr.assnsystem.dto.po



#配置上传文件地址 (工程同级目录下)
fileUpload:
  location:
    path: /upload_tmp/

localip: http://localhost:8082


