server:
  port: 8082



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/assn_system?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xrr.assnsystem.dto.po


